server.port: 9999

spring:
  application.name: gateway
  cloud:
    gateway.server.webflux:
      routes:
        - id: delivery-tracking-route
          uri: lb://DELIVERY-TRACKING
          predicates:
            - Path=/api/v1/deliveries/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
        - id: courier-management-route
          uri: lb://COURIER-MANAGEMENT
          predicates:
            - Path=/api/v1/couriers/**
        - id: courier-management-public-route
          uri: lb://COURIER-MANAGEMENT
          predicates:
            - Path=/public/couriers
            - Method=GET
          filters:
            - RewritePath=/public/couriers, /api/v1/couriers

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/