server:
  port: 9999

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: delivery-tracking-docs
          uri: lb://DELIVERY-TRACKING
          predicates:
            - Path=/delivery-tracking/v3/api-docs
          filters:
            - StripPrefix=1

        - id: courier-management-docs
          uri: lb://COURIER-MANAGEMENT
          predicates:
            - Path=/courier-management/v3/api-docs
          filters:
            - StripPrefix=1

        - id: delivery-tracking-route
          uri: lb://DELIVERY-TRACKING
          predicates:
            - Path=/api/v1/deliveries/**
            - Method=GET,POST,PUT,DELETE,OPTIONS
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: INTERNAL_SERVER_ERROR,BAD_GATEWAY
                methods: GET,PUT
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 30ms
                  factor: 2
                timeout: 400ms
            - name: CircuitBreaker
              args:
                name: delivery-tracking-route-circuit-breaker
                statusCodes:
                  - 500
                  - 502
                  - 504

        - id: courier-management-route
          uri: lb://COURIER-MANAGEMENT
          predicates:
            - Path=/api/v1/couriers/**

        - id: courier-management-public-route
          uri: lb://COURIER-MANAGEMENT
          predicates:
            - Path=/public/couriers
            - Method=GET
          filters:
            - RewritePath=/public/couriers,/api/v1/couriers

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10000
    instances:
      delivery-tracking-route-circuit-breaker:
        baseConfig: default
        waitDurationInOpenState: 5000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Aggregated API
        url: /v3/api-docs-aggregated
  api-docs:
    enabled: true
