server:
  port: 8080

spring:
  application:
    name: courier-management
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:postgresql://postgres:5432/courierdb
    username: postgres
    password: postgres
  kafka:
    consumer:
      bootstrap-servers: kafka:9090
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: courier-management
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: '*'
        spring.json.type.mapping:
          delivery-placed-event:com.carlosSerafimm.courier.management.infrastructure.DeliveryPlacedIntegrationEvent,
          delivery-picked-up-event:com.fasterxml.jackson.databind.JsonNode,
          delivery-fulfilled-event:com.carlosSerafimm.courier.management.infrastructure.DeliveryFulfilledIntegrationEvent
eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

